### ISSUE TITLE
임시 URL을 통한 사용자 구매 목록 페이지가 구현되어야 합니다.

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCWebManager#1]
@DevelopDestroyer @devdotlog 

아래 2개의 API와 연관된 사용자 구매 목록 페이지가 구현되어야 합니다.

https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%9D%BC%ED%9A%8C%EC%9A%A9-%EA%B5%AC%EB%A7%A4%EB%AA%A9%EB%A1%9D-uri-%EC%83%9D%EC%84%B1-%EC%9A%94%EC%B2%AD

https://github.com/dcblock/wiki/wiki/DCCaffeAPI-%EC%A0%95%EC%9D%98#%EC%9D%BC%ED%9A%8C%EC%9A%A9-%EA%B5%AC%EB%A7%A4%EB%AA%A9%EB%A1%9D-uri%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%82%B4%EC%97%AD-%EC%A1%B0%ED%9A%8C

**Comment by DevelopDestroyer** [comment]
구현이 완료되었습니다. 이슈를 닫습니다.
