### ISSUE TITLE
문구 오류

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCWebManager#12]
청구액에는 N&N 이라고 표시
날짜에는 1970-1-1 이 추가로 표시

![image](https://user-images.githubusercontent.com/6669011/50582144-9abc4a80-0ea3-11e9-837c-1d4561cba8c8.png)

**Comment by DevelopDestroyer** [comment]
청구액 부분 수정 완료하였습니다.
5000이 "5,000"으로 바뀌고, 2000이 "2,000"으로 바뀌면서
청구액 연산과정에서 숫자가 아닌것을 연산하려다보니 에러가 발생한 거였네요.

**Comment by DevelopDestroyer** [comment]
취소일이 0일 경우 유닉스 시간을 변환하지 않고 -으로 표시하도록 수정.
이슈를 닫습니다.
