### ISSUE TITLE
Copyright에 년도 추가 요청

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCWebManager#13]
Copyright에 년도가 빠졌습니다. [링크: 올바른 저작권 표시](https://m.blog.naver.com/PostView.nhn?blogId=anicheon&logNo=220405640519&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

![image](https://user-images.githubusercontent.com/6669011/50582238-3a79d880-0ea4-11e9-88d8-3e0fb7d88a88.png)

참고로 디지캡 홈페이지에 다음과 같이 표기되어 있는데, 잘못된 표현입니다.
```
Copyright© DigiCAP All Rights Reserved.
해석하면 저작권, 저작권 X년도 부터 디지캡꺼다.
```

**Comment by DevelopDestroyer** [comment]
그럼 2018년부터라고 하면 돼나요??

**Comment by devdotlog** [comment]
@DevelopDestroyer 
```
```

**Comment by DevelopDestroyer** [comment]
footer 뷰단에 
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
추가하여 수정하였습니다.

이슈를 닫습니다.
