### ISSUE TITLE
로그인 화면에 스크롤이 필요없는 상태인데 스크롤이 생김

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCWebManager#15]
로그인 화면에서 하단에 표시할 콘텐츠가 없는데, 스크롤이 생깁니다.

![image](https://user-images.githubusercontent.com/6669011/50582553-bbd26a80-0ea6-11e9-9bf1-a3dde2f28167.png)

**Comment by DevelopDestroyer** [comment]
스크롤바를 제거하였습니다. 이슈를 닫습니다.
