### ISSUE TITLE
네트워크가 불안정할 경우 Exception

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCWebManager#20]
오전에 발생한 500 에러는 WebManager -> DCAdmin 요청이 실패한 상황.
네트워크가 불안정해서 Post 요청이 Exception 발생.

![image](https://user-images.githubusercontent.com/6669011/51901369-dabb1280-23fa-11e9-8733-da6925777320.png)

[WebManager UserService 71 line](https://github.com/dcblock/DCWebManager/blob/taeho/DCWebManager/src/main/java/com/digicaps/dcwebmanager/service/UserService.java)에서 Exception 처리 없이 아래와 같이 Spring으로 exception을 throw 하면
Spring은 서버에서 에러가 발생했기 때문에 500으로 처리

```java
// restTemplate 이 실제로 요청이 하는 곳이 이기 때문에 이곳에서 Exception을 catch 해야 함
ResponseEntity<String> response = restTemplate.exchange(reqUrl, HttpMethod.POST, entity, String.class);
```

```java
public ResponseEntity RegistUserInfo(HttpServletRequest request) throws Exception // Spring에게 throw{
    	HttpSession session = request.getSession(true);
    	Map<String, Object> retMap = new HashMap<String, Object>();
    	int res = userService.RegistUserInfo(session.getAttribute("access_token").toString(), session.getAttribute("token_type").toString(),
```

네트워크 안정화되면서 동일한 문제가 발생하지는 않았지만
확인이 되었으니까 해당 부분 수정해주세요.

**Comment by DevelopDestroyer** [comment]
수정하여 commit/push 하였습니다.
