### ISSUE TITLE
admin 계정 패스워드 변경

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCWebManager#23]
admin 계정의 패스워드 변경이 필요합니다.
admin 계정의 패스워드가 추측하기 쉬운 문제가 있습니다. 

만약에 상용에 admin 계정으로 로그인 성공하면 메뉴삭제, 사용자 삭제가 가능하기 때문에 
해당 문제에 대한 처리가 시급합니다.

**Comment by bojung-dev** [comment]
비밀번호를 임시로 변경하여 경본에 전달하도록 합시다.
비밀번호를 어렵게 변경한 사유와 변경된 비밀번호를 서상호가 경본 문준영 정채리 신정근 3명에게 메일을 보내주세요.

이후 다음 패치 일정과 반영할 이슈들을 선정하여 진행합시다.

**Comment by Beagleme** [comment]
@devdotlog @bojung-dev 
해당 이슈에 대해서는 개발 및 테스트는 끝마친 상태입니다. 개발서버에 올려서 다른 서버와 연동 테스트 후에 다음 패치 일정에 반영하면 될 것 같습니다.

**Comment by devdotlog** [comment]
임시로 상용 Web Manager의 admin 계정 패스워드를 업데이트하였고
경영지원실 문준영, 신정근, 정채리에 공유하였습니다.
