### ISSUE TITLE
검색종료날짜가 검색시작날짜보다 이전이면 에러페이지 응답됨

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCWebManager#3]
검색 구간의 
검색 종료 날짜가 검색 시작 날짜보다 이전이면 
Error Page가 표시됩니다.

![image](https://user-images.githubusercontent.com/14744923/50580756-fed81200-0e95-11e9-9407-d2019c93bc57.png)

![image](https://user-images.githubusercontent.com/14744923/50580757-05ff2000-0e96-11e9-829d-c8652b365796.png)

**Comment by DevelopDestroyer** [comment]
프론트단에서 시작일이 종료일보다 늦을 경우 검색이 돼지 않도록 방어처리 하였습니다. 이슈를 닫습니다.
