### ISSUE TITLE
Login 이후에 Logout 방법이 없습니다.

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCWebManager#4]
![image](https://user-images.githubusercontent.com/14744923/50580812-cab12100-0e96-11e9-80a5-953072486f24.png)
![image](https://user-images.githubusercontent.com/14744923/50580821-e6b4c280-0e96-11e9-9e95-3c8c1dd01a67.png)

**Comment by DevelopDestroyer** [comment]
로그아웃 기능 추가하였습니다.
이슈를 닫습니다.
