### ISSUE TITLE
사용자 등록 - RF Card 등록 팝업 UI 수정

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCWebManager#5]
![image](https://user-images.githubusercontent.com/14744923/50580954-49f32480-0e98-11e9-8c90-1317729a1838.png)

![image](https://user-images.githubusercontent.com/14744923/50581048-1ebd0500-0e99-11e9-9933-91fd3b3484d2.png)

![image](https://user-images.githubusercontent.com/14744923/50581062-3eecc400-0e99-11e9-91f5-43572b938787.png)

**Comment by DevelopDestroyer** [comment]
반영되었습니다. 이슈를 닫습니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
![image](https://user-images.githubusercontent.com/6669011/50581837-c853c480-0ea0-11e9-9095-96f2a1d4fffd.png)

다음의 문구에서 마침표 추가해주세요.
```
지금 단말기에 카드를 대주세요. 자동으로 입력 됩니다.
```

**Comment by DevelopDestroyer** [comment]
반영완료하였습니다. 이슈를 닫습니다.
