### ISSUE TITLE
까페 관리 - 카테고리/메뉴 관리 - 메뉴 정보 수정 팝업의 출력 위치가 상단에 출력됨

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCWebManager#6]
![image](https://user-images.githubusercontent.com/14744923/50581023-d271c500-0e98-11e9-81f1-147d443613df.png)

![image](https://user-images.githubusercontent.com/14744923/50581072-5af06580-0e99-11e9-98fd-8eea3fe731d7.png)

**Comment by bojung-dev** [comment]
@DevelopDestroyer  @devdotlog 
이건 문제가 아니라면 그냥 두세요.
상세 내역 조회의 width가 넓게 하여 날자를 개별로 표시해주세요.

날짜는 월별로 조회하는 것이기 때문에
년도까지 표시해서 보여줄 필요는 없을 것 같습니다.
월/일 정도만 표시해서 보여주면 "width" 사용을 줄일 수 있을 것 같습니다.

임시 URL로 보여지는 사용자 내역도 마찬가지로 "날짜를 표시할 때는 월과 일만 표시하면 되겠습니다.

**Comment by DevelopDestroyer** [comment]
@bojung-dev 
일단... 부트스트랩에서 제공하는 엑스트라라지 사이즈로 수정하였는데요,,
변경하고보니 날짜를 줄이지 않는 상태가 테이블 필드간 간격이 충분하고 보기에는 괜찮아 보입니다.
이슈를 닫습니다.
