### ISSUE TITLE
사이드 메뉴 상단의 로고 영역의 문구 수정

### ISSUE THREAD

**Issue by bojung-dev** [dcblock/DCWebManager#8]
![image](https://user-images.githubusercontent.com/14744923/50581245-53ca5700-0e9b-11e9-8769-19b4fb9b26a0.png)

**Comment by DevelopDestroyer** [comment]
반영하였습니다.

**Comment by devdotlog** [comment]
@DevelopDestroyer 
![image](https://user-images.githubusercontent.com/6669011/50581720-81b19a80-0e9f-11e9-894b-c1c85bf70655.png)

문구 수정
D Cafe web manager -> DC Cafe Web Manager

**Comment by DevelopDestroyer** [comment]
수정하였습니다.
