### ISSUE TITLE
[검토 요청]아이콘이 서로 바뀐건 아닌지 

### ISSUE THREAD

**Issue by devdotlog** [dcblock/DCWebManager#9]
![image](https://user-images.githubusercontent.com/6669011/50581762-ff75a600-0e9f-11e9-83ff-b9d5fa7c1c4c.png)

메뉴를 닫았을 때와 메뉴가 열려 있을 때 아이콘이 바뀌어야 하는게 아닌지 검토 요청 드립니다.
"엑스" 일때 메뉴가 열려 있고, 메뉴가 없을때는 "메뉴" 아이콘으로 보이는게 맞는게 아닌지.

**Comment by DevelopDestroyer** [comment]
확인 해보니 원래 저게 맞습니다.
토글버튼의 관점의 차이같긴한데요...
"현재 상태를 보여주느냐" or "이걸 누르면 이렇게 된다"
